<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VintageStory-XRay</AssemblyName>
    <RootNamespace>VintageStoryXRay</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <VintageStory>$(VINTAGE_STORY)</VintageStory>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintageStory)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VintageStory)/VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(VintageStory)/Lib/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyModInfo" AfterTargets="Build">
    <MakeDir Directories="$(OutputPath)/mod" />
    <Copy SourceFiles="modinfo.json" DestinationFolder="$(OutputPath)/mod" />
  </Target>
</Project>
